### ISSUE TITLE
unknown bug | unable to start service

### ISSUE THREAD

**Issue by heartpolik** [kangkang520/node-project-manager#1]
/usr/lib/node_modules/node-project-manager/bin/node-project-manager.js:15
async function main() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)

**Comment by kangkang520** [comment]
it looks like your nodejs version is too low to run this script, and pm2 is a powerful util to manage nodejs projects now, you can try it.😁
